name: Python and Node Application CI

on:
  push:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node dependencies
        run: npm install newman

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup-and-build
    services:
      docker:
        image: docker:20.10.8
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_BUILDKIT: 1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node dependencies
        run: npm install newman

      - name: Build and run tests for each microservice
        run: |
          for service in calc; do
            docker build -t $service-test -f $service/Dockerfile .
            docker run -d --name $service-container $service-test
            newman run tests/calc_ut.postman_collection.json
            docker stop $service-container
            docker rm $service-container
          done

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node dependencies
        run: npm install newman

      - name: Build Docker Compose
        run: docker compose build

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Run integration tests
        run: newman run tests/integration.postman_collection.json

      - name: Stop Docker Compose services
        run: docker compose down
