name: Python Application CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install Newman
        run: npm install newman

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
